title = "Comment √ßa va cette semaine&nbsp;?"

why = [
    "L'objectif principal de ce questionnaire est de mieux appr√©hender le moral √† Etalab pendant le confinement, semaine par semaine. Un autre objectif est de permettre √† chacun et chacune de s'exprimer de mani√®re anonyme si il ou elle le souhaite.",
    "A travers les r√©sultats, nous cherchons notamment √† identifier d'√©ventuelles baisses de moral collectives, voire individuelles √† travers le champ texte libre.",
    "Id√©alement, les r√©sultats du questionnaire peuvent servir de base de discussion pour identifier des actions concr√®tes √† mettre en oeuvre.",
    "<a href=\"/report\">Une visualisation des r√©ponses agr√©g√©es est accessible √† tous.</a> Les donn√©es quantitatives sont anonymes et les demandes d'aides ou probl√®mes qui pourraient r√©identifier les r√©pondants ne sont pas int√©gr√©s dans les r√©sultats agr√©g√©s publics.",
    "Les r√©sultats seront lus par la <em>task force</em> animation interne, actuellement compos√©e de Alexandre, Soizic et Olivier. Des √©l√©ments pr√©cis peuvent √™tre partag√©s avec Perica en cas de besoin.",
]

[[fields]]
position = "top"
name = "mood"
type = "radio"
label = "Mon moral"
options = [
    [ "tres_bien", "üòÄ",],
    [ "bien", "üôÇ",],
    [ "moyen", "üòê",],
    [ "pas_bien", "üôÅ",],
]
required = true
size = "lg"
hint = "C'est le seul champ obligatoire üòâ"

[[fields]]
position = "top"
name = "thoughts"
label = "Besoin d'aide ? Un probl√®me ? Une suggestion ? Un coup de gueule ? C'est ici !"
type = "textarea"
required = false
hint = "Ces commentaires ne sont pas publics."

[[fields]]
position = "below"
name = "mood_vs_last_week"
type = "radio"
label = "Par rapport √† la semaine derni√®re, je vais‚Ä¶"
options = [
    [ "same", "Pareil",],
    [ "better", "Mieux",],
    [ "worse", "Moins bien",],
]
required = false

[[fields]]
position = "below"
name = "fatigue"
type = "radio"
label = "Mon √©tat de fatigue"
options = [
    [ "not_tired", "Pas fatigu√© du tout",],
    [ "a_little_tired", "Un peu fatigu√©",],
    [ "tired", "Fatigu√©",],
    [ "very_tired", "Tr√®s fatigu√©",],
]
required = false

[[fields]]
position = "below"
name = "fatigue_vs_last_week"
type = "radio"
label = "Par rapport √† la semaine derni√®re, je suis‚Ä¶"
options = [
    [ "same", "Aussi fatigu√©",],
    [ "better", "Moins fatigu√©",],
    [ "worse", "Plus fatigu√©",],
]
required = false

[[fields]]
position = "below"
name = "workload"
type = "radio"
label = "Ma charge de travail cette semaine a √©t√©‚Ä¶"
options = [ [ "good", "Adapt√©e",], [ "too_much", "Trop importante (je me suis senti d√©pass√©.e)",], [ "not_enough", "Pas assez importante (je me suis senti d√©soeuvr√©.e)",],]
required = false

[[fields]]
position = "below"
name = "proximity_project"
type = "radio"
label = "J‚Äôai l‚Äôimpression de me sentir proche des autres membres de mon √©quipe projet"
options = [ [ "very_no", "Pas du tout d‚Äôaccord",], [ "no", "Pas d‚Äôaccord",], [ "yes", "D‚Äôaccord",], [ "very_yes", "Tout √† fait d‚Äôaccord",],]
required = false

[[fields]]
position = "below"
name = "proximity_etalab"
type = "radio"
label = "J‚Äôai l‚Äôimpression de me sentir proche des autres membres de l‚Äô√©quipe Etalab"
options = [ [ "very_no", "Pas du tout d‚Äôaccord",], [ "no", "Pas d‚Äôaccord",], [ "yes", "D‚Äôaccord",], [ "very_yes", "Tout √† fait d‚Äôaccord",],]
required = false

[[fields]]
position = "below"
name = "seminaire_ideas"
label = "Mes id√©es d‚Äôactivit√©s ou de travaux collectifs pour le prochain s√©minaire virtuel : th√®mes, formats, fun ou pas fun... Toutes les id√©es sont les bienvenues !"
type = "textarea"
required = false

[[fields]]
position = "below"
name = "seminaire_takeaway"
label = "Mes attentes vis-√†-vis de ce s√©minaire, i.e. je consid√©rerai que ce s√©minaire est un succ√®s si..."
type = "textarea"
required = false

[[fields]]
position = "below"
name = "seminaire_date"
label = "Mes disponibilit√©s pour ce s√©minaire"
type = "link"
link = "https://framadate.org/PZ8L15kCWbPYeKdi"
required = false
