title = "Comment Ã§a va cette semaine&nbsp;?"

why = [
    "L'objectif principal de ce questionnaire est de mieux apprÃ©hender le moral Ã  Etalab pendant le confinement, semaine par semaine. Un autre objectif est de permettre Ã  chacun et chacune de s'exprimer de maniÃ¨re anonyme si il ou elle le souhaite.",
    "A travers les rÃ©sultats, nous cherchons notamment Ã  identifier d'Ã©ventuelles baisses de moral collectives, voire individuelles Ã  travers le champ texte libre.",
    "IdÃ©alement, les rÃ©sultats du questionnaire peuvent servir de base de discussion pour identifier des actions concrÃ¨tes Ã  mettre en oeuvre.",
    "<a href=\"/report\">Une visualisation des rÃ©ponses agrÃ©gÃ©es est accessible Ã  tous.</a> Les donnÃ©es quantitatives sont anonymes et les demandes d'aides ou problÃ¨mes qui pourraient rÃ©identifier les rÃ©pondants ne sont pas intÃ©grÃ©s dans les rÃ©sultats agrÃ©gÃ©s publics.",
    "Les rÃ©sultats seront lus par la <em>task force</em> animation interne, actuellement composÃ©e de Alexandre, Soizic et Olivier. Des Ã©lÃ©ments prÃ©cis peuvent Ãªtre partagÃ©s avec Perica en cas de besoin.",
]

[[fields]]
position = "top"
name = "mood"
type = "radio"
label = "Mon moral"
options = [
    [ "tres_bien", "ğŸ˜€",],
    [ "bien", "ğŸ™‚",],
    [ "moyen", "ğŸ˜",],
    [ "pas_bien", "ğŸ™",],
]
required = true
size = "lg"
hint = "C'est le seul champ obligatoire ğŸ˜‰"

[[fields]]
position = "top"
name = "thoughts"
label = "Besoin d'aide ? Un problÃ¨me ? Une suggestion ? Un coup de gueule ? C'est ici !"
type = "textarea"
required = false
hint = "Ces commentaires ne sont pas publics."

[[fields]]
position = "below"
name = "mood_vs_last_week"
type = "radio"
label = "Par rapport Ã  la semaine derniÃ¨re, je vaisâ€¦"
options = [
    [ "same", "Pareil",],
    [ "better", "Mieux",],
    [ "worse", "Moins bien",],
]
required = false

[[fields]]
position = "below"
name = "fatigue"
type = "radio"
label = "Mon Ã©tat de fatigue"
options = [
    [ "not_tired", "Pas fatiguÃ© du tout",],
    [ "a_little_tired", "Un peu fatiguÃ©",],
    [ "tired", "FatiguÃ©",],
    [ "very_tired", "TrÃ¨s fatiguÃ©",],
]
required = false

[[fields]]
position = "below"
name = "fatigue_vs_last_week"
type = "radio"
label = "Par rapport Ã  la semaine derniÃ¨re, je suisâ€¦"
options = [
    [ "same", "Aussi fatiguÃ©",],
    [ "better", "Moins fatiguÃ©",],
    [ "worse", "Plus fatiguÃ©",],
]
required = false

[[fields]]
position = "below"
name = "workload"
type = "radio"
label = "Ma charge de travail cette semaine a Ã©tÃ©â€¦"
options = [ [ "good", "AdaptÃ©e",], [ "too_much", "Trop importante (je me suis senti dÃ©passÃ©.e)",], [ "not_enough", "Pas assez importante (je me suis senti dÃ©soeuvrÃ©.e)",],]
required = false

[[fields]]
position = "below"
name = "proximity_project"
type = "radio"
label = "Jâ€™ai lâ€™impression de me sentir proche des autres membres de mon Ã©quipe projet"
options = [ [ "very_no", "Pas du tout dâ€™accord",], [ "no", "Pas dâ€™accord",], [ "yes", "Dâ€™accord",], [ "very_yes", "Tout Ã  fait dâ€™accord",],]
required = false

[[fields]]
position = "below"
name = "proximity_etalab"
type = "radio"
label = "Jâ€™ai lâ€™impression de me sentir proche des autres membres de lâ€™Ã©quipe Etalab"
options = [ [ "very_no", "Pas du tout dâ€™accord",], [ "no", "Pas dâ€™accord",], [ "yes", "Dâ€™accord",], [ "very_yes", "Tout Ã  fait dâ€™accord",],]
required = false

[[fields]]
position = "below"
name = "proximity_etalab_important"
type = "radio"
label = "Me sentir proche des autres membres de lâ€™Ã©quipe Etalab est important pour moi"
options = [ [ "very_no", "Pas du tout dâ€™accord",], [ "no", "Pas dâ€™accord",], [ "yes", "Dâ€™accord",], [ "very_yes", "Tout Ã  fait dâ€™accord",],]
required = false
